-- Seed: closed category dictionary + default subcategories (plan sekcja 2)
-- Safe to re-run: uses upsert semantics.

insert into categories (id, name, icon, color, sort_order) values
  ('zywnosc-i-dom', 'Żywność i dom', 'shopping-cart', '#16a34a', 0),
  ('mieszkanie', 'Mieszkanie', 'home', '#2563eb', 1),
  ('transport', 'Transport', 'car', '#ea580c', 2),
  ('zdrowie', 'Zdrowie', 'heart-pulse', '#dc2626', 3),
  ('dzieci', 'Dzieci', 'baby', '#db2777', 4),
  ('rozrywka-i-czas-wolny', 'Rozrywka i czas wolny', 'popcorn', '#9333ea', 5),
  ('subskrypcje-i-uslugi-cyfrowe', 'Subskrypcje i usługi cyfrowe', 'monitor-smartphone', '#0891b2', 6),
  ('ubrania-i-akcesoria', 'Ubrania i akcesoria', 'shirt', '#c026d3', 7),
  ('uroda-i-sport', 'Uroda i sport', 'dumbbell', '#0d9488', 8),
  ('edukacja', 'Edukacja', 'graduation-cap', '#4f46e5', 9),
  ('podroze', 'Podróże', 'plane', '#0284c7', 10),
  ('finanse', 'Finanse', 'landmark', '#525252', 11),
  ('oszczednosci-i-inwestycje', 'Oszczędności i inwestycje', 'piggy-bank', '#059669', 12),
  ('prezenty-i-darowizny', 'Prezenty i darowizny', 'gift', '#e11d48', 13),
  ('inne', 'Inne', 'ellipsis', '#71717a', 14)
on conflict (id) do update set name = excluded.name, icon = excluded.icon, color = excluded.color, sort_order = excluded.sort_order;

insert into subcategories (id, category_id, household_id, name, sort_order) values
  ('zywnosc-i-dom__spozywcze', 'zywnosc-i-dom', null, 'Spożywcze', 0),
  ('zywnosc-i-dom__nabial-i-jaja', 'zywnosc-i-dom', null, 'Nabiał i jaja', 1),
  ('zywnosc-i-dom__mieso-i-ryby', 'zywnosc-i-dom', null, 'Mięso i ryby', 2),
  ('zywnosc-i-dom__warzywa-i-owoce', 'zywnosc-i-dom', null, 'Warzywa i owoce', 3),
  ('zywnosc-i-dom__pieczywo', 'zywnosc-i-dom', null, 'Pieczywo', 4),
  ('zywnosc-i-dom__napoje', 'zywnosc-i-dom', null, 'Napoje', 5),
  ('zywnosc-i-dom__alkohol', 'zywnosc-i-dom', null, 'Alkohol', 6),
  ('zywnosc-i-dom__slodycze-i-przekaski', 'zywnosc-i-dom', null, 'Słodycze i przekąski', 7),
  ('zywnosc-i-dom__chemia-domowa', 'zywnosc-i-dom', null, 'Chemia domowa', 8),
  ('zywnosc-i-dom__higiena-i-kosmetyki', 'zywnosc-i-dom', null, 'Higiena i kosmetyki', 9),
  ('zywnosc-i-dom__artykuly-dla-zwierzat', 'zywnosc-i-dom', null, 'Artykuły dla zwierząt', 10),
  ('mieszkanie__czynsz-najem', 'mieszkanie', null, 'Czynsz / najem', 0),
  ('mieszkanie__rata-kredytu', 'mieszkanie', null, 'Rata kredytu', 1),
  ('mieszkanie__prad', 'mieszkanie', null, 'Prąd', 2),
  ('mieszkanie__gaz', 'mieszkanie', null, 'Gaz', 3),
  ('mieszkanie__woda-i-scieki', 'mieszkanie', null, 'Woda i ścieki', 4),
  ('mieszkanie__smieci', 'mieszkanie', null, 'Śmieci', 5),
  ('mieszkanie__internet', 'mieszkanie', null, 'Internet', 6),
  ('mieszkanie__tv', 'mieszkanie', null, 'TV', 7),
  ('mieszkanie__ubezpieczenie-mieszkania', 'mieszkanie', null, 'Ubezpieczenie mieszkania', 8),
  ('mieszkanie__remont-i-wyposazenie', 'mieszkanie', null, 'Remont i wyposażenie', 9),
  ('mieszkanie__meble-i-agd', 'mieszkanie', null, 'Meble i AGD', 10),
  ('transport__paliwo', 'transport', null, 'Paliwo', 0),
  ('transport__ladowanie-ev', 'transport', null, 'Ładowanie EV', 1),
  ('transport__komunikacja-miejska', 'transport', null, 'Komunikacja miejska', 2),
  ('transport__taxi-przejazdy', 'transport', null, 'Taxi / przejazdy', 3),
  ('transport__serwis-i-czesci', 'transport', null, 'Serwis i części', 4),
  ('transport__ubezpieczenie-oc-ac', 'transport', null, 'Ubezpieczenie OC/AC', 5),
  ('transport__przeglady-i-oplaty', 'transport', null, 'Przeglądy i opłaty', 6),
  ('transport__parking-i-autostrady', 'transport', null, 'Parking i autostrady', 7),
  ('zdrowie__leki-i-apteka', 'zdrowie', null, 'Leki i apteka', 0),
  ('zdrowie__wizyty-lekarskie', 'zdrowie', null, 'Wizyty lekarskie', 1),
  ('zdrowie__stomatolog', 'zdrowie', null, 'Stomatolog', 2),
  ('zdrowie__badania', 'zdrowie', null, 'Badania', 3),
  ('zdrowie__rehabilitacja', 'zdrowie', null, 'Rehabilitacja', 4),
  ('zdrowie__okulista-i-optyka', 'zdrowie', null, 'Okulista i optyka', 5),
  ('zdrowie__ubezpieczenie-zdrowotne', 'zdrowie', null, 'Ubezpieczenie zdrowotne', 6),
  ('dzieci__zlobek-przedszkole', 'dzieci', null, 'Żłobek / przedszkole', 0),
  ('dzieci__szkola-i-wyprawka', 'dzieci', null, 'Szkoła i wyprawka', 1),
  ('dzieci__zajecia-dodatkowe', 'dzieci', null, 'Zajęcia dodatkowe', 2),
  ('dzieci__ubrania', 'dzieci', null, 'Ubrania', 3),
  ('dzieci__zabawki', 'dzieci', null, 'Zabawki', 4),
  ('dzieci__opieka', 'dzieci', null, 'Opieka', 5),
  ('rozrywka-i-czas-wolny__restauracje-i-kawiarnie', 'rozrywka-i-czas-wolny', null, 'Restauracje i kawiarnie', 0),
  ('rozrywka-i-czas-wolny__fast-food', 'rozrywka-i-czas-wolny', null, 'Fast food', 1),
  ('rozrywka-i-czas-wolny__kino-teatr-koncerty', 'rozrywka-i-czas-wolny', null, 'Kino / teatr / koncerty', 2),
  ('rozrywka-i-czas-wolny__gry', 'rozrywka-i-czas-wolny', null, 'Gry', 3),
  ('rozrywka-i-czas-wolny__ksiazki-i-prasa', 'rozrywka-i-czas-wolny', null, 'Książki i prasa', 4),
  ('rozrywka-i-czas-wolny__hobby', 'rozrywka-i-czas-wolny', null, 'Hobby', 5),
  ('rozrywka-i-czas-wolny__wydarzenia-sportowe', 'rozrywka-i-czas-wolny', null, 'Wydarzenia sportowe', 6),
  ('subskrypcje-i-uslugi-cyfrowe__streaming-wideo', 'subskrypcje-i-uslugi-cyfrowe', null, 'Streaming wideo', 0),
  ('subskrypcje-i-uslugi-cyfrowe__muzyka', 'subskrypcje-i-uslugi-cyfrowe', null, 'Muzyka', 1),
  ('subskrypcje-i-uslugi-cyfrowe__chmura-i-software', 'subskrypcje-i-uslugi-cyfrowe', null, 'Chmura i software', 2),
  ('subskrypcje-i-uslugi-cyfrowe__ai-narzedzia', 'subskrypcje-i-uslugi-cyfrowe', null, 'AI / narzędzia', 3),
  ('subskrypcje-i-uslugi-cyfrowe__telefon', 'subskrypcje-i-uslugi-cyfrowe', null, 'Telefon', 4),
  ('subskrypcje-i-uslugi-cyfrowe__aplikacje-mobilne', 'subskrypcje-i-uslugi-cyfrowe', null, 'Aplikacje mobilne', 5),
  ('ubrania-i-akcesoria__odziez', 'ubrania-i-akcesoria', null, 'Odzież', 0),
  ('ubrania-i-akcesoria__obuwie', 'ubrania-i-akcesoria', null, 'Obuwie', 1),
  ('ubrania-i-akcesoria__dodatki', 'ubrania-i-akcesoria', null, 'Dodatki', 2),
  ('ubrania-i-akcesoria__bizuteria-i-zegarki', 'ubrania-i-akcesoria', null, 'Biżuteria i zegarki', 3),
  ('ubrania-i-akcesoria__pralnia-i-naprawy', 'ubrania-i-akcesoria', null, 'Pralnia i naprawy', 4),
  ('uroda-i-sport__fryzjer', 'uroda-i-sport', null, 'Fryzjer', 0),
  ('uroda-i-sport__kosmetyczka', 'uroda-i-sport', null, 'Kosmetyczka', 1),
  ('uroda-i-sport__silownia-karnet', 'uroda-i-sport', null, 'Siłownia / karnet', 2),
  ('uroda-i-sport__sprzet-sportowy', 'uroda-i-sport', null, 'Sprzęt sportowy', 3),
  ('uroda-i-sport__suplementy', 'uroda-i-sport', null, 'Suplementy', 4),
  ('edukacja__kursy-i-szkolenia', 'edukacja', null, 'Kursy i szkolenia', 0),
  ('edukacja__studia', 'edukacja', null, 'Studia', 1),
  ('edukacja__materialy', 'edukacja', null, 'Materiały', 2),
  ('edukacja__certyfikaty', 'edukacja', null, 'Certyfikaty', 3),
  ('edukacja__korepetycje', 'edukacja', null, 'Korepetycje', 4),
  ('podroze__nocleg', 'podroze', null, 'Nocleg', 0),
  ('podroze__bilety-lotnicze-kolejowe', 'podroze', null, 'Bilety lotnicze / kolejowe', 1),
  ('podroze__wynajem-auta', 'podroze', null, 'Wynajem auta', 2),
  ('podroze__wyzywienie-w-podrozy', 'podroze', null, 'Wyżywienie w podróży', 3),
  ('podroze__atrakcje', 'podroze', null, 'Atrakcje', 4),
  ('podroze__ubezpieczenie-podrozne', 'podroze', null, 'Ubezpieczenie podróżne', 5),
  ('finanse__odsetki-i-prowizje', 'finanse', null, 'Odsetki i prowizje', 0),
  ('finanse__ubezpieczenia-na-zycie', 'finanse', null, 'Ubezpieczenia na życie', 1),
  ('finanse__podatki', 'finanse', null, 'Podatki', 2),
  ('finanse__oplaty-bankowe', 'finanse', null, 'Opłaty bankowe', 3),
  ('finanse__splata-dlugu', 'finanse', null, 'Spłata długu', 4),
  ('oszczednosci-i-inwestycje__poduszka-finansowa', 'oszczednosci-i-inwestycje', null, 'Poduszka finansowa', 0),
  ('oszczednosci-i-inwestycje__ike-ikze', 'oszczednosci-i-inwestycje', null, 'IKE / IKZE', 1),
  ('oszczednosci-i-inwestycje__inwestycje', 'oszczednosci-i-inwestycje', null, 'Inwestycje', 2),
  ('oszczednosci-i-inwestycje__cele-oszczednosciowe', 'oszczednosci-i-inwestycje', null, 'Cele oszczędnościowe', 3),
  ('prezenty-i-darowizny__prezenty', 'prezenty-i-darowizny', null, 'Prezenty', 0),
  ('prezenty-i-darowizny__swieta-i-okazje', 'prezenty-i-darowizny', null, 'Święta i okazje', 1),
  ('prezenty-i-darowizny__charytatywne', 'prezenty-i-darowizny', null, 'Charytatywne', 2),
  ('prezenty-i-darowizny__wesela-i-urodziny', 'prezenty-i-darowizny', null, 'Wesela i urodziny', 3),
  ('inne__nieprzypisane', 'inne', null, 'Nieprzypisane', 0),
  ('inne__gotowka-wyplata-z-bankomatu', 'inne', null, 'Gotówka / wypłata z bankomatu', 1),
  ('inne__zwroty', 'inne', null, 'Zwroty', 2),
  ('inne__korekty', 'inne', null, 'Korekty', 3)
on conflict (id) do update set name = excluded.name, sort_order = excluded.sort_order;
