-- Seed: closed category dictionary + default subcategories (plan sekcja 2)

INSERT INTO categories (id, name, icon, color, sort_order) VALUES ('zywnosc-i-dom', 'Żywność i dom', 'shopping-cart', '#16a34a', 0);
INSERT INTO categories (id, name, icon, color, sort_order) VALUES ('mieszkanie', 'Mieszkanie', 'home', '#2563eb', 1);
INSERT INTO categories (id, name, icon, color, sort_order) VALUES ('transport', 'Transport', 'car', '#ea580c', 2);
INSERT INTO categories (id, name, icon, color, sort_order) VALUES ('zdrowie', 'Zdrowie', 'heart-pulse', '#dc2626', 3);
INSERT INTO categories (id, name, icon, color, sort_order) VALUES ('dzieci', 'Dzieci', 'baby', '#db2777', 4);
INSERT INTO categories (id, name, icon, color, sort_order) VALUES ('rozrywka-i-czas-wolny', 'Rozrywka i czas wolny', 'popcorn', '#9333ea', 5);
INSERT INTO categories (id, name, icon, color, sort_order) VALUES ('subskrypcje-i-uslugi-cyfrowe', 'Subskrypcje i usługi cyfrowe', 'monitor-smartphone', '#0891b2', 6);
INSERT INTO categories (id, name, icon, color, sort_order) VALUES ('ubrania-i-akcesoria', 'Ubrania i akcesoria', 'shirt', '#c026d3', 7);
INSERT INTO categories (id, name, icon, color, sort_order) VALUES ('uroda-i-sport', 'Uroda i sport', 'dumbbell', '#0d9488', 8);
INSERT INTO categories (id, name, icon, color, sort_order) VALUES ('edukacja', 'Edukacja', 'graduation-cap', '#4f46e5', 9);
INSERT INTO categories (id, name, icon, color, sort_order) VALUES ('podroze', 'Podróże', 'plane', '#0284c7', 10);
INSERT INTO categories (id, name, icon, color, sort_order) VALUES ('finanse', 'Finanse', 'landmark', '#525252', 11);
INSERT INTO categories (id, name, icon, color, sort_order) VALUES ('oszczednosci-i-inwestycje', 'Oszczędności i inwestycje', 'piggy-bank', '#059669', 12);
INSERT INTO categories (id, name, icon, color, sort_order) VALUES ('prezenty-i-darowizny', 'Prezenty i darowizny', 'gift', '#e11d48', 13);
INSERT INTO categories (id, name, icon, color, sort_order) VALUES ('inne', 'Inne', 'ellipsis', '#71717a', 14);

INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('zywnosc-i-dom__spozywcze', 'zywnosc-i-dom', NULL, 'Spożywcze', 0);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('zywnosc-i-dom__nabial-i-jaja', 'zywnosc-i-dom', NULL, 'Nabiał i jaja', 1);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('zywnosc-i-dom__mieso-i-ryby', 'zywnosc-i-dom', NULL, 'Mięso i ryby', 2);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('zywnosc-i-dom__warzywa-i-owoce', 'zywnosc-i-dom', NULL, 'Warzywa i owoce', 3);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('zywnosc-i-dom__pieczywo', 'zywnosc-i-dom', NULL, 'Pieczywo', 4);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('zywnosc-i-dom__napoje', 'zywnosc-i-dom', NULL, 'Napoje', 5);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('zywnosc-i-dom__alkohol', 'zywnosc-i-dom', NULL, 'Alkohol', 6);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('zywnosc-i-dom__slodycze-i-przekaski', 'zywnosc-i-dom', NULL, 'Słodycze i przekąski', 7);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('zywnosc-i-dom__chemia-domowa', 'zywnosc-i-dom', NULL, 'Chemia domowa', 8);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('zywnosc-i-dom__higiena-i-kosmetyki', 'zywnosc-i-dom', NULL, 'Higiena i kosmetyki', 9);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('zywnosc-i-dom__artykuly-dla-zwierzat', 'zywnosc-i-dom', NULL, 'Artykuły dla zwierząt', 10);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('mieszkanie__czynsz-najem', 'mieszkanie', NULL, 'Czynsz / najem', 0);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('mieszkanie__rata-kredytu', 'mieszkanie', NULL, 'Rata kredytu', 1);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('mieszkanie__prad', 'mieszkanie', NULL, 'Prąd', 2);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('mieszkanie__gaz', 'mieszkanie', NULL, 'Gaz', 3);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('mieszkanie__woda-i-scieki', 'mieszkanie', NULL, 'Woda i ścieki', 4);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('mieszkanie__smieci', 'mieszkanie', NULL, 'Śmieci', 5);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('mieszkanie__internet', 'mieszkanie', NULL, 'Internet', 6);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('mieszkanie__tv', 'mieszkanie', NULL, 'TV', 7);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('mieszkanie__ubezpieczenie-mieszkania', 'mieszkanie', NULL, 'Ubezpieczenie mieszkania', 8);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('mieszkanie__remont-i-wyposazenie', 'mieszkanie', NULL, 'Remont i wyposażenie', 9);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('mieszkanie__meble-i-agd', 'mieszkanie', NULL, 'Meble i AGD', 10);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('transport__paliwo', 'transport', NULL, 'Paliwo', 0);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('transport__ladowanie-ev', 'transport', NULL, 'Ładowanie EV', 1);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('transport__komunikacja-miejska', 'transport', NULL, 'Komunikacja miejska', 2);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('transport__taxi-przejazdy', 'transport', NULL, 'Taxi / przejazdy', 3);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('transport__serwis-i-czesci', 'transport', NULL, 'Serwis i części', 4);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('transport__ubezpieczenie-oc-ac', 'transport', NULL, 'Ubezpieczenie OC/AC', 5);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('transport__przeglady-i-oplaty', 'transport', NULL, 'Przeglądy i opłaty', 6);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('transport__parking-i-autostrady', 'transport', NULL, 'Parking i autostrady', 7);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('zdrowie__leki-i-apteka', 'zdrowie', NULL, 'Leki i apteka', 0);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('zdrowie__wizyty-lekarskie', 'zdrowie', NULL, 'Wizyty lekarskie', 1);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('zdrowie__stomatolog', 'zdrowie', NULL, 'Stomatolog', 2);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('zdrowie__badania', 'zdrowie', NULL, 'Badania', 3);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('zdrowie__rehabilitacja', 'zdrowie', NULL, 'Rehabilitacja', 4);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('zdrowie__okulista-i-optyka', 'zdrowie', NULL, 'Okulista i optyka', 5);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('zdrowie__ubezpieczenie-zdrowotne', 'zdrowie', NULL, 'Ubezpieczenie zdrowotne', 6);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('dzieci__zlobek-przedszkole', 'dzieci', NULL, 'Żłobek / przedszkole', 0);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('dzieci__szkola-i-wyprawka', 'dzieci', NULL, 'Szkoła i wyprawka', 1);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('dzieci__zajecia-dodatkowe', 'dzieci', NULL, 'Zajęcia dodatkowe', 2);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('dzieci__ubrania', 'dzieci', NULL, 'Ubrania', 3);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('dzieci__zabawki', 'dzieci', NULL, 'Zabawki', 4);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('dzieci__opieka', 'dzieci', NULL, 'Opieka', 5);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('rozrywka-i-czas-wolny__restauracje-i-kawiarnie', 'rozrywka-i-czas-wolny', NULL, 'Restauracje i kawiarnie', 0);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('rozrywka-i-czas-wolny__fast-food', 'rozrywka-i-czas-wolny', NULL, 'Fast food', 1);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('rozrywka-i-czas-wolny__kino-teatr-koncerty', 'rozrywka-i-czas-wolny', NULL, 'Kino / teatr / koncerty', 2);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('rozrywka-i-czas-wolny__gry', 'rozrywka-i-czas-wolny', NULL, 'Gry', 3);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('rozrywka-i-czas-wolny__ksiazki-i-prasa', 'rozrywka-i-czas-wolny', NULL, 'Książki i prasa', 4);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('rozrywka-i-czas-wolny__hobby', 'rozrywka-i-czas-wolny', NULL, 'Hobby', 5);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('rozrywka-i-czas-wolny__wydarzenia-sportowe', 'rozrywka-i-czas-wolny', NULL, 'Wydarzenia sportowe', 6);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('subskrypcje-i-uslugi-cyfrowe__streaming-wideo', 'subskrypcje-i-uslugi-cyfrowe', NULL, 'Streaming wideo', 0);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('subskrypcje-i-uslugi-cyfrowe__muzyka', 'subskrypcje-i-uslugi-cyfrowe', NULL, 'Muzyka', 1);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('subskrypcje-i-uslugi-cyfrowe__chmura-i-software', 'subskrypcje-i-uslugi-cyfrowe', NULL, 'Chmura i software', 2);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('subskrypcje-i-uslugi-cyfrowe__ai-narzedzia', 'subskrypcje-i-uslugi-cyfrowe', NULL, 'AI / narzędzia', 3);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('subskrypcje-i-uslugi-cyfrowe__telefon', 'subskrypcje-i-uslugi-cyfrowe', NULL, 'Telefon', 4);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('subskrypcje-i-uslugi-cyfrowe__aplikacje-mobilne', 'subskrypcje-i-uslugi-cyfrowe', NULL, 'Aplikacje mobilne', 5);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('ubrania-i-akcesoria__odziez', 'ubrania-i-akcesoria', NULL, 'Odzież', 0);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('ubrania-i-akcesoria__obuwie', 'ubrania-i-akcesoria', NULL, 'Obuwie', 1);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('ubrania-i-akcesoria__dodatki', 'ubrania-i-akcesoria', NULL, 'Dodatki', 2);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('ubrania-i-akcesoria__bizuteria-i-zegarki', 'ubrania-i-akcesoria', NULL, 'Biżuteria i zegarki', 3);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('ubrania-i-akcesoria__pralnia-i-naprawy', 'ubrania-i-akcesoria', NULL, 'Pralnia i naprawy', 4);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('uroda-i-sport__fryzjer', 'uroda-i-sport', NULL, 'Fryzjer', 0);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('uroda-i-sport__kosmetyczka', 'uroda-i-sport', NULL, 'Kosmetyczka', 1);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('uroda-i-sport__silownia-karnet', 'uroda-i-sport', NULL, 'Siłownia / karnet', 2);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('uroda-i-sport__sprzet-sportowy', 'uroda-i-sport', NULL, 'Sprzęt sportowy', 3);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('uroda-i-sport__suplementy', 'uroda-i-sport', NULL, 'Suplementy', 4);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('edukacja__kursy-i-szkolenia', 'edukacja', NULL, 'Kursy i szkolenia', 0);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('edukacja__studia', 'edukacja', NULL, 'Studia', 1);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('edukacja__materialy', 'edukacja', NULL, 'Materiały', 2);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('edukacja__certyfikaty', 'edukacja', NULL, 'Certyfikaty', 3);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('edukacja__korepetycje', 'edukacja', NULL, 'Korepetycje', 4);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('podroze__nocleg', 'podroze', NULL, 'Nocleg', 0);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('podroze__bilety-lotnicze-kolejowe', 'podroze', NULL, 'Bilety lotnicze / kolejowe', 1);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('podroze__wynajem-auta', 'podroze', NULL, 'Wynajem auta', 2);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('podroze__wyzywienie-w-podrozy', 'podroze', NULL, 'Wyżywienie w podróży', 3);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('podroze__atrakcje', 'podroze', NULL, 'Atrakcje', 4);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('podroze__ubezpieczenie-podrozne', 'podroze', NULL, 'Ubezpieczenie podróżne', 5);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('finanse__odsetki-i-prowizje', 'finanse', NULL, 'Odsetki i prowizje', 0);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('finanse__ubezpieczenia-na-zycie', 'finanse', NULL, 'Ubezpieczenia na życie', 1);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('finanse__podatki', 'finanse', NULL, 'Podatki', 2);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('finanse__oplaty-bankowe', 'finanse', NULL, 'Opłaty bankowe', 3);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('finanse__splata-dlugu', 'finanse', NULL, 'Spłata długu', 4);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('oszczednosci-i-inwestycje__poduszka-finansowa', 'oszczednosci-i-inwestycje', NULL, 'Poduszka finansowa', 0);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('oszczednosci-i-inwestycje__ike-ikze', 'oszczednosci-i-inwestycje', NULL, 'IKE / IKZE', 1);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('oszczednosci-i-inwestycje__inwestycje', 'oszczednosci-i-inwestycje', NULL, 'Inwestycje', 2);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('oszczednosci-i-inwestycje__cele-oszczednosciowe', 'oszczednosci-i-inwestycje', NULL, 'Cele oszczędnościowe', 3);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('prezenty-i-darowizny__prezenty', 'prezenty-i-darowizny', NULL, 'Prezenty', 0);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('prezenty-i-darowizny__swieta-i-okazje', 'prezenty-i-darowizny', NULL, 'Święta i okazje', 1);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('prezenty-i-darowizny__charytatywne', 'prezenty-i-darowizny', NULL, 'Charytatywne', 2);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('prezenty-i-darowizny__wesela-i-urodziny', 'prezenty-i-darowizny', NULL, 'Wesela i urodziny', 3);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('inne__nieprzypisane', 'inne', NULL, 'Nieprzypisane', 0);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('inne__gotowka-wyplata-z-bankomatu', 'inne', NULL, 'Gotówka / wypłata z bankomatu', 1);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('inne__zwroty', 'inne', NULL, 'Zwroty', 2);
INSERT INTO subcategories (id, category_id, household_id, name, sort_order) VALUES ('inne__korekty', 'inne', NULL, 'Korekty', 3);
