// Augments the auto-generated CloudflareEnv (cloudflare-env.d.ts, gitignored,
// regenerated by `wrangler types`) with secrets that aren't declared in
// wrangler.jsonc — those are pushed with `wrangler secret put` instead, so
// wrangler doesn't know about them when generating types.
interface CloudflareEnv {
  /** Set via `wrangler secret put ANTHROPIC_API_KEY` (see README). Used for receipt-scan AI. */
  ANTHROPIC_API_KEY: string;
}
