// Augments the auto-generated CloudflareEnv (cloudflare-env.d.ts, gitignored,
// regenerated by `wrangler types`) with secrets that aren't declared in
// wrangler.jsonc — those are pushed with `wrangler secret put` instead, so
// wrangler doesn't know about them when generating types.
interface CloudflareEnv {
  /** Set via `wrangler secret put ANTHROPIC_API_KEY` (see README). Used for receipt-scan AI. */
  ANTHROPIC_API_KEY: string;
  /** VAPID key pair for Web Push, generated once with `npx web-push generate-vapid-keys` (see README). */
  VAPID_PUBLIC_KEY: string;
  VAPID_PRIVATE_KEY: string;
  /** "mailto:you@example.com" — required by the Web Push protocol as a contact for push services. */
  VAPID_SUBJECT: string;
}
